apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: web
          image: x1wins/cw-ovp
          imagePullPolicy: Always
          args:
            - bash
            - -c
            - rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e production
          ports:
            - containerPort: 3000
          resources: {}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: env-s3-prod
            - name: AWS_CLOUDFRONT_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: AWS_CLOUDFRONT_DOMAIN
                  name: env-s3-prod
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: env-s3-prod
            - name: BUCKET
              valueFrom:
                configMapKeyRef:
                  key: BUCKET
                  name: env-s3-prod
            - name: CABLE_REDIS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: CABLE_REDIS_SERVER_URL
                  name: env-prod
            - name: CDN_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: CDN_BUCKET
                  name: env-s3-prod
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_NAME
                  name: env-prod
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PASSWORD
                  name: env-prod
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PORT
                  name: env-prod
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env-prod
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_USERNAME
                  name: env-prod
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-prod
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-prod
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-prod
            - name: RAILS_SERVE_STATIC_FILES
              valueFrom:
                configMapKeyRef:
                  key: RAILS_SERVE_STATIC_FILES
                  name: env-prod
            - name: REDIS_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_CLIENT_URL
                  name: env-prod
            - name: REDIS_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_SERVER_URL
                  name: env-prod
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  key: REGION
                  name: env-s3-prod
            - name: WEB_LOGO_URL
              valueFrom:
                configMapKeyRef:
                  key: WEB_LOGO_URL
                  name: env-prod
            - name: WEB_TITLE
              valueFrom:
                configMapKeyRef:
                  key: WEB_TITLE
                  name: env-prod
            - name: RAILS_MASTER_KEY
              valueFrom:
                configMapKeyRef:
                  key: RAILS_MASTER_KEY
                  name: env-prod
            - name: RAILS_ACTION_CABLE_URL
              valueFrom:
                configMapKeyRef:
                  key: RAILS_ACTION_CABLE_URL
                  name: env-prod
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - web
              topologyKey: "kubernetes.io/hostname"
